change list to array

In [1]:
import numpy as np

In [2]:
list = [5,9,8,7,5]
lists = np.array(list)
lists

array([5, 9, 8, 7, 5])

what if we use print command

In [3]:
print(lists)

[5 9 8 7 5]


dimension

In [4]:
lists.ndim

1

In [5]:
b = np.array([[4, 8, 6, 9], [7, 6, 9,2]])
b.ndim

2

shape

In [6]:
lists.shape

(5,)

In [7]:
b.shape

(2, 4)

Type

In [8]:
lists.dtype

dtype('int32')

In [9]:
b.dtype

dtype('int32')

File storge size 

In [10]:
lists.nbytes

20

In [11]:
b.nbytes

32

for bigger dimension lists

In [13]:
c = np.array([[[5,8],[8,9]],[[8,5],[3,6]]])
c


array([[[5, 8],
        [8, 9]],

       [[8, 5],
        [3, 6]]])

In [14]:
print(c)

[[[5 8]
  [8 9]]

 [[8 5]
  [3 6]]]


In [15]:
c.ndim

3

In [16]:
c.shape


(2, 2, 2)

In [17]:
c.dtype

dtype('int32')

In [18]:
c.nbytes

32

to find no of elements ## size of array

In [19]:
lists.size

5

In [20]:
b.size

8

In [21]:
c.size

8

to find item size ????

In [22]:
lists.itemsize

4

In [23]:
b.itemsize

4

In [24]:
c.itemsize

4

few arthemetic operation  to  elements in the array

In [25]:
lists+20

array([25, 29, 28, 27, 25])

In [27]:
list*5

[5, 9, 8, 7, 5, 5, 9, 8, 7, 5, 5, 9, 8, 7, 5, 5, 9, 8, 7, 5, 5, 9, 8, 7, 5]

In [38]:
lists*5

array([25, 45, 40, 35, 25])

In [31]:
list/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [32]:
list-5


TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [33]:
list**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [34]:
b+10

array([[14, 18, 16, 19],
       [17, 16, 19, 12]])

In [35]:
c+8

array([[[13, 16],
        [16, 17]],

       [[16, 13],
        [11, 14]]])

In [36]:
c*5

array([[[25, 40],
        [40, 45]],

       [[40, 25],
        [15, 30]]])

In [37]:
b*5

array([[20, 40, 30, 45],
       [35, 30, 45, 10]])

dtype complex

In [41]:
a = np.array([1, 0, 3], dtype = complex) 
print (a)

[1.+0.j 0.+0.j 3.+0.j]


Changing values

In [42]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [43]:
# Get a specific element [r, c]
a[0, 5]

6

In [44]:
# Get a specific row 
p=a[1, :]
print(p)

[ 8  9 10 11 12 13 14]


In [45]:
# Get a specific column
a[:, 1]

array([2, 9])

In [46]:
 # [startindex:endindex:stepsize]
a[:, 1:-1:2]

array([[ 2,  4,  6],
       [ 9, 11, 13]])

In [47]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [50]:
a[1,5] = 5

a[:,5] = [2,4]
print(a)

[[ 1  2  1  4  5  2  7]
 [ 8  9  2 11 12  4 14]]


In [51]:
a[1,5] = 5

a[:,5] = [2]
print(a)

[[ 1  2  1  4  5  2  7]
 [ 8  9  2 11 12  2 14]]


In [52]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [53]:
# Get specific element (work outside in)
b[0,1,1]

4

Initializing Different Types of Arrays

In [2]:
# All 0s matrix
import numpy as np
np.zeros((2,3,6,5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0

In [3]:
# All 1s matrix
np.ones((4,2,2,2), dtype='int32')

array([[[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]],


       [[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]],


       [[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]],


       [[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]]])

In [4]:
# Any other number
np.full((2,2,3), 50)

array([[[50, 50, 50],
        [50, 50, 50]],

       [[50, 50, 50],
        [50, 50, 50]]])

In [9]:
# Any other number (full_like)
a = np.array([5, 8, 9,8,6])
np.full_like(a, 4)

array([4, 4, 4, 4, 4])

In [10]:
# Any other number (full_like)
a = np.array([[5, 8, 9,8,6],[5,4,6,3,6]])
np.full_like(a, 4)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [11]:
a = [[5, 8, 9,8,6],[5,4,6,3,6]]
np.full_like(a, 4)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [12]:
# Random decimal numbers
np.random.rand(4,2,1)

array([[[0.67616904],
        [0.49784553]],

       [[0.10555565],
        [0.66314213]],

       [[0.47830954],
        [0.76385687]],

       [[0.05599105],
        [0.28947239]]])

In [13]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.54382037, 0.16690042],
       [0.27751101, 0.84192869],
       [0.47587917, 0.94630532],
       [0.24077836, 0.39703181]])

In [14]:
# Random Integer values
np.random.randint(-4,8, size=(4,4))

array([[ 1, -4, -2,  1],
       [ 0,  0,  2,  5],
       [ 7,  4,  5,  4],
       [ 2,  1, -1,  4]])

In [15]:
np.random.randint(-4,100, size=(4,4))

array([[26, 38,  4,  7],
       [42, 20, 49, 92],
       [60, 23, 61, 12],
       [20, 17, 24, 37]])

In [16]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
np.identity(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [18]:
np.identity(5,3)

TypeError: Cannot interpret '3' as a data type

In [19]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [20]:
# Repeat an array
arr = np.array([[1,2,3],[5,8,6]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [5 8 6]
 [5 8 6]
 [5 8 6]]


In [21]:
arr = np.array([[1,2,3],[5,8,6]])
r1 = np.repeat(arr,3, axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]
 [5 5 5 8 8 8 6 6 6]]


In [22]:
arr = np.array([[1,2,3],[5,8,6]])
r1 = np.repeat(arr,3, axis=3)
print(r1)

AxisError: axis 3 is out of bounds for array of dimension 2

In [23]:
arr = np.array([[1,2,3],[5,8,6]])
r1 = np.repeat(arr,3, axis=2)
print(r1)

AxisError: axis 2 is out of bounds for array of dimension 2

In [24]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [25]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[2:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


ValueError: could not broadcast input array from shape (3,3) into shape (2,3)

In [26]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


ValueError: could not broadcast input array from shape (3,3) into shape (4,3)

In [27]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[2:,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]]


In [30]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[2:,0:-3] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


ValueError: could not broadcast input array from shape (3,3) into shape (3,2)

In [31]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[2:,0:3] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [0. 0. 0. 1. 1.]
 [0. 9. 0. 1. 1.]
 [0. 0. 0. 1. 1.]]


copy arrys

In [32]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)
print(b)
b

[1 2 3]
[100   2   3]


array([100,   2,   3])

maths 

In [34]:
a = np.array([5,6,9,7])

In [35]:
a/2

array([2.5, 3. , 4.5, 3.5])

In [36]:
a-6

array([-1,  0,  3,  1])

In [37]:
a**5

array([ 3125,  7776, 59049, 16807], dtype=int32)

trignometric operations

In [38]:
a = np.array([0, 30, 60, 90])

In [39]:
np.cos(a)

array([ 1.        ,  0.15425145, -0.95241298, -0.44807362])

In [40]:
np.sin(a)

array([ 0.        , -0.98803162, -0.30481062,  0.89399666])

linear algebra

In [42]:
#determinant
np.linalg.det(a)

LinAlgError: 1-dimensional array given. Array must be at least two-dimensional

In [43]:
b = np.array([[5,6,3],[8,6,9]])
np.linalg.det(b)

LinAlgError: Last 2 dimensions of the array must be square

In [44]:
b = np.array([[5,6,3],[8,6,9],[4,3,1]])
np.linalg.det(b)

62.99999999999999

In [46]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)   #product of matrix

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [48]:
b = np.array([[5,6,3],[8,6,9],[4,3,1]])
np.min(b)

1

In [49]:
np.max(b)

9

In [50]:
np.max(b,axis=0)

array([8, 6, 9])

In [51]:
np.max(b,axis=1)

array([6, 9, 4])

In [52]:
np.max(b,axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [53]:
np.sum(b, axis=0)

array([17, 15, 13])

In [55]:
np.sum(b, axis=1)

array([14, 23,  8])

Rearranging Arrays

In [57]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [58]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((1,8))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4 5 6 7 8]]


In [59]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2,v1,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [60]:
# horizantal stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.hstack([v1,v2,v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8])

In [66]:
# horizantal stacking vectors
v1 = np.array([[1,2,3,4],[5,6,8,3]])
v2 = np.array([[5,6,7,8],[8,3,4,7]])

np.hstack((v1,v2,v1,v2,v1))

array([[1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4],
       [5, 6, 8, 3, 8, 3, 4, 7, 5, 6, 8, 3, 8, 3, 4, 7, 5, 6, 8, 3]])